# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
has: &has_acc true
# might want to find better values on acceleration, check:
# https://www.universal-robots.com/articles/ur/robot-care-maintenance/max-joint-torques/
acc: &acc0 1
acc: &acc1 1
acc: &acc2 1

joint_limits:
  finger_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: false
    max_acceleration: 0
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: *has_acc
    max_acceleration: *acc1
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: *has_acc
    max_acceleration: *acc1
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: *has_acc
    max_acceleration: *acc2
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: *has_acc
    max_acceleration: *acc0
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: *has_acc
    max_acceleration: *acc0
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: *has_acc
    max_acceleration: *acc0
